catalogoleitura/AppCatalogo/urls.py
from django.urls import path
from . import views

app_name = 'livros'

urlpatterns = [
    path('livros/', views.listarLivros, name='listarLivros'),
    path('livros/formLivro.html', views.criarLivro, name='criarLivro'),
    path('livros/formLivroComApi.html', views.adicionarLivroComApi, name='adicionarLivroComApi'),  
    path('livros/<str:isbn>', views.detalharLivro, name='detalharLivro'),
    path('livros/editar/<str:isbn>/', views.editarLivro, name='editarLivro'),
    path('livros/excluir/<str:isbn>/', views.excluirLivro, name='excluirLivro'),

    path('usuario/', views.listaUser, name='listaUser'),
    path('usuario/<int:usuarioId>/', views.detalharUser, name='detalharUser'),
    path('usuario/criar/', views.criarUser, name='criarUser'),
    path('usuario/<int:usuarioId>/editar/', views.editarUser, name='editarUser'),
    path('usuario/<int:usuarioId>/excluir/', views.excluirUser, name='excluirUser'),
]

catalogoleitura/catalogoleitura/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('catalogoleitura/', include('AppCatalogo.urls'))
]

catalogoleitura/AppCatalogo/models.py
from django.db import models

class Livro(models.Model):
    titulo = models.CharField(max_length=200)
    autor = models.CharField(max_length=100)
    isbn = models.CharField(max_length=13, unique=True)
    data_publi = models.CharField(max_length=20)
    lido = models.BooleanField(default=False)
    nota = models.FloatField(null=True, blank=True)
    comentarios = models.TextField(null=True, blank=True)
    
    def __str__(self):
        return self.titulo


class Usuario(models.Model):
    usuario = models.CharField(max_length=100)
    email = models.EmailField(max_length=200)
    livro = models.ForeignKey(Livro, on_delete=models.SET_NULL, null=True, blank=True)  
    
    def __str__(self):
        return self.usuario

catalogoleitura/AppCatalogo/forms.py
from django import forms
from .models import Livro
from .models import Usuario

class LivroForm(forms.ModelForm):
    class Meta:
        model = Livro
        fields = ['titulo', 'autor', 'isbn', 'data_publi', 'lido', 'nota', 'comentarios']
        
class UsuarioForm(forms.ModelForm):
    class Meta:
        model = Usuario
        fields = ['usuario', 'email', 'livro']
        
class LivroAPIForm(forms.Form):
    isbn = forms.CharField(
        max_length=13,
        required=True,
        widget=forms.TextInput(attrs={'placeholder': 'Digite o ISBN'})
    )

catalogoleitura/AppCatalogo/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Livro, Usuario
from .forms import LivroForm, UsuarioForm, LivroAPIForm
import requests
from datetime import datetime

def listarLivros(request):
    livros = Livro.objects.all()
    if not livros:  
        livros = None  

    return render(request, 'livros/listarLivro.html', {'livros': livros})


def detalharLivro(request, isbn):
    livro = get_object_or_404(Livro, isbn=isbn)
    return render(request, 'livros/detalharLivro.html', {'livro': livro})

def criarLivro(request):
    if request.method == 'POST':
        form = LivroForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('livros:listarLivros')
    else:
        form = LivroForm()
    return render(request, 'livros/formLivro.html', {'form': form})

def editarLivro(request, isbn):
    livro = get_object_or_404(Livro, isbn=isbn)
    if request.method == 'POST':
        form = LivroForm(request.POST, instance=livro)
        if form.is_valid():
            form.save()
            return redirect('livros:listarLivros')
    else:
        form = LivroForm(instance=livro)
    return render(request, 'livros/formLivro.html', {'form': form})

def excluirLivro(request, isbn):
    livro = get_object_or_404(Livro, isbn=isbn)
    if request.method == 'POST':
        livro.delete()
        return redirect('livros:listarLivros')
    return render(request, 'livros/confirmarExclusao.html', {'livro': livro})

def adicionarLivroComApi(request):
    if request.method == 'POST':
        form = LivroAPIForm(request.POST)
        if form.is_valid():
            isbn = form.cleaned_data['isbn']
            
            url = f"https://openlibrary.org/api/books?bibkeys=ISBN:{isbn}&format=json&jscmd=data"
            response = requests.get(url)
            
            if response.status_code == 200:
                data = response.json()
                
                if f"ISBN:{isbn}" in data:
                    detalhes = data[f"ISBN:{isbn}"]
                    
                    titulo = detalhes.get('title', 'Título não disponível')
                    autores = detalhes.get('authors', [])
                    autor = ', '.join(author.get('name', 'Autor desconhecido') for author in autores)
                    

                    data_publi_raw = detalhes.get('publish_date', None)
                    if data_publi_raw:
                        try:
                            datetime.strptime(data_publi_raw, '%Y-%m-%d')
                            data_publi = datetime.strptime(data_publi_raw, '%Y-%m-%d').strftime('%d/%m/%Y')
                        except ValueError:
                            try:
                                datetime.strptime(data_publi_raw, '%Y-%m')
                                data_publi = datetime.strptime(data_publi_raw, '%Y-%m').strftime('%m/%Y')
                            except ValueError:
                                data_publi = 'Data de publicação não disponível'
                    else:
                        data_publi = 'Data de publicação não disponível'
                    
                    livro = Livro(
                        titulo=titulo,
                        autor=autor,
                        isbn=isbn,
                        data_publi=data_publi
                    )
                    livro.save()
                    return redirect('livros:listarLivros')
                else:
                    form.add_error('isbn', 'Detalhes do livro não encontrados na API.')
            else:
                form.add_error('isbn', 'Erro ao acessar a API do Open Library.')
    else:
        form = LivroAPIForm()
    
    return render(request, 'livros/formLivroComApi.html', {'form': form})

def listaUser(request):
    usuarios = Usuario.objects.all()
    return render(request, 'usuarios/listaUser.html', {'usuarios': usuarios})

def detalharUser(request, usuarioId):
    usuario = get_object_or_404(Usuario, id=usuarioId)
    return render(request, 'usuarios/detalharUser.html', {'usuario': usuario})

def criarUser(request):
    if request.method == 'POST':
        form = UsuarioForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('listaUser')
    else:
        form = UsuarioForm()
    
    return render(request, 'usuarios/formUser.html', {'form': form})

def editarUser(request, usuarioId):
    usuario = get_object_or_404(Usuario, id=usuarioId)
    if request.method == 'POST':
        form = UsuarioForm(request.POST, instance=usuario)
        if form.is_valid():
            form.save()
            return redirect('listaUser')
    else:
        form = UsuarioForm(instance=usuario)
    return render(request, 'usuarios/formUser.html', {'form': form})

def excluirUser(request, usuarioId):
    usuario = get_object_or_404(Usuario, id=usuarioId)
    if request.method == 'POST':
        usuario.delete()
        return redirect('listaUser') 
    return render(request, 'usuarios/confirmarExclusao.html', {'usuario': usuario})

catalogoleitura/AppCatalogo/templates/livros/confirmarExclusao.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <title>Confirmar Exclusão</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 20px;
        }
        form {
            margin-bottom: 20px;
        }
        .form-group {
            margin-bottom: 15px;
        }
        .form-group label {
            display: block;
            margin-bottom: 5px;
        }
        .form-group input {
            width: 100%;
            padding: 8px;
            box-sizing: border-box;
        }
        .error-list {
            color: red;
        }
        .error-list li {
            margin-bottom: 5px;
        }
    </style>
</head>
<body>
    <h1>Confirmar Exclusão de Livro</h1>
    <p>Você tem certeza que deseja excluir o livro "{{ livro.titulo }}"?</p>
    <form method="post">
        {% csrf_token %}
        <button type="submit">Confirmar Exclusão</button>
    </form>
    <a href="{% url 'livros:listarLivros' %}">Cancelar</a>
</body>
</html>

catalogoleitura/AppCatalogo/templates/livros/detalharLivro.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <title>Detalhes do Livro</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 20px;
        }
        form {
            margin-bottom: 20px;
        }
        .form-group {
            margin-bottom: 15px;
        }
        .form-group label {
            display: block;
            margin-bottom: 5px;
        }
        .form-group input {
            width: 100%;
            padding: 8px;
            box-sizing: border-box;
        }
        .error-list {
            color: red;
        }
        .error-list li {
            margin-bottom: 5px;
        }
    </style>
</head>
<body>
    <h1>Detalhes do Livro</h1>
    <p><strong>Título:</strong> {{ livro.titulo }}</p>
    <p><strong>Autor:</strong> {{ livro.autor }}</p>
    <p><strong>ISBN:</strong> {{ livro.isbn }}</p>
    <p><strong>Descrição:</strong> {{ livro.descricao }}</p>
    <p><strong>Data de Publicação:</strong> {{ livro.data_publi }}</p>
    <a href="{% url 'livros:listarLivros' %}">Voltar para a lista de livros</a>
    <a href="{% url 'livros:editarLivro' isbn=livro.isbn %}">Editar Livro</a>
    <form action="{% url 'livros:excluirLivro' isbn=livro.isbn %}" method="post">
        {% csrf_token %}
        <button type="submit">Excluir Livro</button>
    </form>
</body>
</html>

catalogoleitura/AppCatalogo/templates/livros/formLivro.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <title>Formulário de Livro</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 20px;
        }
        form {
            margin-bottom: 20px;
        }
        .form-group {
            margin-bottom: 15px;
        }
        .form-group label {
            display: block;
            margin-bottom: 5px;
        }
        .form-group input {
            width: 100%;
            padding: 8px;
            box-sizing: border-box;
        }
        .error-list {
            color: red;
        }
        .error-list li {
            margin-bottom: 5px;
        }
    </style>
</head>
<body>
    <h1>{% if form.instance.pk %}Editar Livro{% else %}Adicionar Livro{% endif %}</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Salvar</button>
    </form>
    <a href="{% url 'livros:listarLivros' %}">Cancelar</a>
</body>
</html>

catalogoleitura/AppCatalogo/templates/livros/formLivroComApi.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <title>Formulário de Livro via API</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 20px;
        }
        form {
            margin-bottom: 20px;
        }
        .form-group {
            margin-bottom: 15px;
        }
        .form-group label {
            display: block;
            margin-bottom: 5px;
        }
        .form-group input {
            width: 100%;
            padding: 8px;
            box-sizing: border-box;
        }
        .error-list {
            color: red;
        }
        .error-list li {
            margin-bottom: 5px;
        }
    </style>
</head>
<body>
    <h1>Adicionar Livro via API</h1>
    <form method="post">
        {% csrf_token %}
        <div class="form-group">
            {{ form.isbn.label_tag }}:
            {{ form.isbn }}
        </div>
        <button type="submit">Buscar e Adicionar</button>
        
        {% if form.errors %}
            <div class="error-list">
                <ul>
                    {% for field, error_list in form.errors.items %}
                        {% for error in error_list %}
                            <li>{{ error }}</li>
                        {% endfor %}
                    {% endfor %}
                </ul>
            </div>
        {% endif %}
    </form>
    <a href="{% url 'livros:listarLivros' %}">Cancelar</a>
</body>
</html>

catalogoleitura/AppCatalogo/templates/livros/listarLivro.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <title>Listar Livros</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 20px;
        }
        form {
            margin-bottom: 20px;
        }
        .form-group {
            margin-bottom: 15px;
        }
        .form-group label {
            display: block;
            margin-bottom: 5px;
        }
        .form-group input {
            width: 100%;
            padding: 8px;
            box-sizing: border-box;
        }
        .error-list {
            color: red;
        }
        .error-list li {
            margin-bottom: 5px;
        }
    </style>
</head>
<body>
    <h1>Listagem de Livros</h1>
    {% if livros %}
    <ul>
        {% for livro in livros %}
            <li>
                <a href="{% url 'livros:detalharLivro' isbn=livro.isbn %}">{{ livro.titulo }}</a>
                - {{ livro.autor }}
                <form action="{% url 'livros:excluirLivro' isbn=livro.isbn %}" method="post">
                    {% csrf_token %}
                    <button type="submit">Excluir</button>
                </form>
            </li>
        {% endfor %}
    </ul>
    {% else %}
    <p>Nenhum livro cadastrado.</p>
    {% endif %}
    <a href="{% url 'livros:criarLivro' %}">Adicionar Livro Manualmente</a>
    <a href="{% url 'livros:adicionarLivroComApi' %}">Adicionar Livro via API</a>

</body>
</html>

catalogoleitura/AppCatalogo/templates/usuarios/confirmarExclusao.html
<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <title>Confirmar Exclusão</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 20px;
        }
        form {
            margin-bottom: 20px;
        }
        .form-group {
            margin-bottom: 15px;
        }
        .form-group label {
            display: block;
            margin-bottom: 5px;
        }
        .form-group input {
            width: 100%;
            padding: 8px;
            box-sizing: border-box;
        }
        .error-list {
            color: red;
        }
        .error-list li {
            margin-bottom: 5px;
        }
    </style>
</head>
<body>
    <h1>Excluir Usuário</h1>
    <p>Tem certeza de que deseja excluir o usuário "{{ usuario.usuario }}"?</p>
    <form method="post">
        {% csrf_token %}
        <button type="submit">Excluir</button>
        <a href="{% url 'livros:detalharUser' usuario.id %}">Cancelar</a>
    </form>
</body>
</html>

catalogoleitura/AppCatalogo/templates/usuarios/detalharUser.html
<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <title>Detalhes do Usuário</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 20px;
        }
        form {
            margin-bottom: 20px;
        }
        .form-group {
            margin-bottom: 15px;
        }
        .form-group label {
            display: block;
            margin-bottom: 5px;
        }
        .form-group input {
            width: 100%;
            padding: 8px;
            box-sizing: border-box;
        }
        .error-list {
            color: red;
        }
        .error-list li {
            margin-bottom: 5px;
        }
    </style>
</head>
<body>
    <h1>{{ usuario.usuario }}</h1>
    <p><strong>Email:</strong> {{ usuario.email }}</p>
    <p><strong>Livros:</strong> 
        <ul>
            {% for livro in usuario.livros.all %}
                <li>{{ livro.titulo }}</li>
            {% endfor %}
        </ul>
    </p>
    <a href="{% url 'livros:editarUser' usuario.id %}">Editar</a>
    <a href="{% url 'livros:excluirUser' usuario.id %}">Excluir</a>
    <a href="{% url 'livros:listaUser' %}">Voltar à Lista</a>
</body>
</html>

catalogoleitura/AppCatalogo/templates/usuarios/formUser.html
<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <title>Cadastrar Usuário</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 20px;
        }
        form {
            margin-bottom: 20px;
        }
        .form-group {
            margin-bottom: 15px;
        }
        .form-group label {
            display: block;
            margin-bottom: 5px;
        }
        .form-group input {
            width: 100%;
            padding: 8px;
            box-sizing: border-box;
        }
        .error-list {
            color: red;
        }
        .error-list li {
            margin-bottom: 5px;
        }
    </style>
</head>
<body>
    <h1>{{ form.instance.id|default_if_none:"Adicionar Novo Usuário" }}</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Salvar</button>
    </form>
    <a href="{% url 'livros:listaUser' %}">Cancelar</a>
</body>
</html>

catalogoleitura/AppCatalogo/templates/usuarios/listaUser.html
<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <title>Lista de Usuários</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 20px;
        }
        form {
            margin-bottom: 20px;
        }
        .form-group {
            margin-bottom: 15px;
        }
        .form-group label {
            display: block;
            margin-bottom: 5px;
        }
        .form-group input {
            width: 100%;
            padding: 8px;
            box-sizing: border-box;
        }
        .error-list {
            color: red;
        }
        .error-list li {
            margin-bottom: 5px;
        }
    </style>
</head>
<body>
    <h1>Lista de Usuários</h1>
    <a href="{% url 'livros:criarUser' %}">Adicionar Novo Usuário</a>
    <ul>
        {% for usuario in usuarios %}
            <li>
                <a href="{% url 'livros:detalharUser' usuario.id %}">{{ usuario.usuario }}</a> - {{ usuario.email }}
            </li>
        {% endfor %}
    </ul>
</body>
</html>